name: wger
version: "2.5.0"
slug: wger
boot: manual
description: boing A free, open source web application for managing your workouts and nutrition.
url: "https://github.com/paalwilliams/homeassistant-addons"
arch:
  - amd64
  - aarch64
init: false
map:
  - media:rw
  - addon_config:rw
ports:
  8000/tcp: 8000
schema:
  SECRET_KEY: str
  SIGNING_KEY: str
  DJANGO_DB_ENGINE: list(django.db.backends.postgresql)?
  DJANGO_DB_HOST: str
  DJANGO_DB_PORT: int?
  DJANGO_DB_DATABASE: str
  DJANGO_DB_USER: str
  DJANGO_DB_PASSWORD: password
  ALLOW_REGISTRATION: bool?
  ALLOW_GUEST_USERS: bool?
  SITE_URL: str?
  TZ: str
options:
  SECRET_KEY: ""
  SIGNING_KEY: ""
  DJANGO_DB_ENGINE: django.db.backends.postgresql
  DJANGO_DB_HOST: ""
  DJANGO_DB_PORT: 5432
  DJANGO_DB_DATABASE: wger
  DJANGO_DB_USER: wger
  DJANGO_DB_PASSWORD: ""
  ALLOW_REGISTRATION: true
  ALLOW_GUEST_USERS: true
  SITE_URL: "http://localhost:8000"
  TZ: America/Los_Angeles
webui: http://[HOST]:[PORT:8000]
legacy: true
ports_description:
  8000/tcp: Web interface port
panel_icon: weight-lifter
panel_title: wger
