name: wger
version: "2.7.0"
slug: wger
boot: manual
description: A free, open source web application for managing your workouts and nutrition.
url: "https://github.com/paalwilliams/homeassistant-addons"
arch:
  - amd64
  - aarch64
init: false
map:
  - media:rw
  - addon_config:rw
ports:
  8000/tcp: 8000
schema:
  SECRET_KEY: str?
  JWT_PRIVATE_KEY: str?
  JWT_PUBLIC_KEY: str?
  DJANGO_DB_ENGINE: list(django.db.backends.postgresql)?
  DJANGO_DB_HOST: str
  DJANGO_DB_PORT: int?
  DJANGO_DB_DATABASE: str
  DJANGO_DB_USER: str
  DJANGO_DB_PASSWORD: password
  ALLOW_REGISTRATION: bool?
  SYNC_EXERCISES_ON_STARTUP: bool?
  WARMUP_EXERCISE_CACHE_ON_STARTUP: bool?
  DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP: bool?
  ALLOW_GUEST_USERS: bool?
  SITE_URL: str?
  CSRF_TRUSTED_ORIGINS: str?
  GUNICORN_CMD_ARGS: str?
  TZ: str
options:
  SECRET_KEY: ""
  JWT_PRIVATE_KEY: ""
  JWT_PUBLIC_KEY: ""
  DJANGO_DB_ENGINE: django.db.backends.postgresql
  DJANGO_DB_HOST: ""
  DJANGO_DB_PORT: 5432
  DJANGO_DB_DATABASE: wger
  DJANGO_DB_USER: wger
  DJANGO_DB_PASSWORD: ""
  ALLOW_REGISTRATION: true
  SYNC_EXERCISES_ON_STARTUP: false
  WARMUP_EXERCISE_CACHE_ON_STARTUP: true
  DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP: false
  ALLOW_GUEST_USERS: true
  SITE_URL: "http://homeassistant.local:8000"
  CSRF_TRUSTED_ORIGINS: "http://homeassistant.local:8000"
  GUNICORN_CMD_ARGS: ""
  TZ: America/Los_Angeles
webui: http://[HOST]:[PORT:8000]
legacy: true
ports_description:
  8000/tcp: Web interface port
panel_icon: mdi:weight-lifter
panel_title: wger
